name: test
on:
  workflow_dispatch:
  push:
    branches:
    - main
    
    
jobs:
  testing:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Git clone repository
      uses: actions/checkout@v3
   
    - name: Install syslog-ng
      run: |
        #cd /tmp
        #wget https://github.com/syslog-ng/syslog-ng/releases/download/syslog-ng-3.26.1/syslog-ng-3.26.1.tar.gz
        #tar -xzf syslog-ng-3.26.1.tar.gz -C .
        #cd syslog-ng-3.26.1
        #./configure && make && sudo make install
        
        git clone https://github.com/balabit/syslog-ng -b syslog-ng-3.26.1
        cd syslog-ng
        dbld/rules tarball
        dbld/rules image-ubuntu-focal
        dbld/rules deb-ubuntu-focal
        cd dbld/build/ubuntu-focal
        get add .
        git commit -m "testing"
        git push
        
        
        
        #wget https://github.com/syslog-ng/syslog-ng/releases/download/syslog-ng-3.26.1/syslog-ng-3.26.1.tar.gz
        #tar -xzf syslog-ng-3.26.1.tar.gz -C .
 
      
      
        #sudo apt-get install syslog-ng=3.26.1
        #sudo cp syslog/syslog-ng.conf /etc/syslog-ng/syslog-ng.conf
        #ps -A | grep syslog
        #pwd
        #ls
        #cd /etc/syslog-ng
        #ls
        #syslog-ng -s