name: test
on:
  workflow_dispatch:
  push:
    branches:
    - main
    
    
jobs:
  testing:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Git clone repository
      uses: actions/checkout@v3
   
    - name: Install syslog-ng
      run: |
        ls
        pwd
        wget http://ftp.us.debian.org/debian/pool/main/s/syslog-ng/syslog-ng-core_3.28.1-2+b1_amd64.deb
        ls
        sudo apt install syslog-ng-core_3.28.1-2+b1_amd64.deb
        echo " "
        syslog-ng --version
        echo " "
        sudo syslog-ng -s
        #cd syslog
        ls
        pwd
        sudo cp syslog-ng.conf /etc/syslog-ng/syslog-ng.conf
      
        #sudo echo "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/Debian_9.0 ./" >> /etc/apt/sources.list.d/syslog-ng-obs.list
        #sudo apt-get update
        #sudo apt install syslog-ng
        #sudo syslog-ng --version
        
        
        
        
        
        #yum install wget
        #wget https://download.copr.fedorainfracloud.org/results/czanik/syslog-ng326epel6/epel-6-x86_64/01324992-syslog-ng/syslog-ng-3.26.1-2.el6.x86_64.rpm
        #rpm -Uvh syslog-ng-3.26.1-2.el6.x86_64.rpm
      
      
        #sudo apt-get update
        #sudo apt-get install alien
        #wget https://snapshot.debian.org/archive/debian/20200304T033001Z/pool/main/s/syslog-ng/syslog-ng_3.25.1-3_all.deb
        #sudo apt install /tmp/syslog-ng_3.25.1-3_all.deb
        #wget https://download.copr.fedorainfracloud.org/results/czanik/syslog-ng326epel6/epel-6-x86_64/01324992-syslog-ng/syslog-ng-3.26.1-2.el6.x86_64.rpm
        #sudo alien -i syslog-ng-3.26.1-2.el6.x86_64.rpm
        #sudo apt install /tmp/syslog-ng_3.26.1-2_amd64.deb
        
        
        #docker pull balabit/syslog-ng:3.26.1
        #sudo apt install dpkg-dev
        #sudo apt install devscripts
        #cd /tmp
        #git clone https://github.com/syslog-ng/syslog-ng -b syslog-ng-3.26.1
        #wget https://github.com/syslog-ng/syslog-ng/archive/refs/tags/syslog-ng-3.25.1.tar.gz
        #tar -xzf syslog-ng-3.26.1.tar.gz -C .
        #cd syslog-ng
        #cd dbld
        #mkdir build
        #cd build
        #wget https://github.com/syslog-ng/syslog-ng/releases/download/syslog-ng-3.26.1/syslog-ng-3.26.1.tar.gz
        #cd ../..
        #dbld/rules image-ubuntu-bionic
        #dbld/rules deb-ubuntu-bionic
        
        #git clone https://github.com/syslog-ng/syslog-ng -b syslog-ng-3.26.1
        #cd syslog-ng
        #dbld/rules tarball
        #dbld/rules image-ubuntu-focal
        #dbld/rules deb-ubuntu-focal
        #cd dbld/build/ubuntu-focal
        #get add .
        #git commit -m "testing"
        #git push
        #yum update
        
        
        
        #wget https://github.com/syslog-ng/syslog-ng/releases/download/syslog-ng-3.26.1/syslog-ng-3.26.1.tar.gz
        #tar -xzf syslog-ng-3.26.1.tar.gz -C .
 
      
      
        #sudo apt-get install syslog-ng=3.26.1
        #sudo cp syslog/syslog-ng.conf /etc/syslog-ng/syslog-ng.conf
        #ps -A | grep syslog
        #pwd
        #ls
        #cd /etc/syslog-ng
        #ls
        #syslog-ng -s