name: Syslog-ng Syntax Check
on:
  workflow_dispatch:
  push:
    branches: ['main']
    #paths: ['syslog-ng/**']
    
jobs:
  syslog-ng-syntax-check:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Git clone repository
      uses: actions/checkout@v3
   
    - name: Install syslog-ng
      run: |
        wget http://ftp.us.debian.org/debian/pool/main/s/syslog-ng/syslog-ng-core_3.28.1-2+b1_amd64.deb
        sudo apt install ./syslog-ng-core_3.28.1-2+b1_amd64.deb
        service syslog-ng start 
        
    - name: Copy syslog-ng.conf from repo to runner
      run: |
        sudo cp -R syslog-ng /etc/syslog-ng
        cat /etc/syslog-ng/syslog-ng.conf
        
    #- name: Create single syslog-ng.conf file from all configs
    #  run: sudo syslog-ng-ctl config -p > /tmp/syslog-ng.conf
    
    - name: Check syntax against configs
      run: |
        #cat /tmp/syslog-ng.conf
        sudo syslog-ng -s