name: test
on:
  workflow_dispatch:
  push:
    branches:
    - main
    
    
jobs:
  testing:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Git clone repository
      uses: actions/checkout@v3
   
    - name: Install syslog-ng
      run: |
        sudo apt-get install syslog-ng
        sudo cp syslog/syslog-ng.conf /etc/syslog-ng/syslog-ng.conf
        ps -A | grep syslog
        pwd
        ls
        cd /etc/syslog-ng
        ls
        syslog-ng -s