name: test
on:
  workflow_dispatch:
  push:
    branches:
    - main
    
    
jobs:
  testing:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: apt-get update
      run: |
        wget -qO - https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install syslog-ng=3.26.1-2
        sudo syslog-ng --version
        echo "test"
        ps -A | grep syslog