name: test
on:
  workflow_dispatch:
  push:
    branches:
    - main
    
    
jobs:
  testing:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: apt-get update
      run: |
        sudo apt-get update