name: Send workflow output to Splunk HEC

on: [push]

jobs:
  send-output:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Send output to Splunk
      uses: splunk/splunk-github-actions/splunk-logging@v0.2.0
      with:
        hec-token: ${{ secrets.SPLUNK_HEC_TOKEN }}
        hec-url: ${{ secrets.SPLUNK_HEC_ENDPOINT }}
        sourcetype: my-sourcetype
        index: my-index
        message: ${{ toJson(steps) }}