name: Send workflow output to Splunk HEC

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  send-output:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: echo
      run: |
        echo "${{ toJson(steps) }}"