name: Send workflow output to Splunk HEC

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  send-output:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Send output to Splunk
      run: |
        curl -k ${{ secrets.SPLUNK_HEC_ENDPOINT }} \
        -H 'Authorization: Splunk ${{ secrets.SPLUNK_HEC_TOKEN }}' \
        -d '{"event":'"$(echo "${{ toJson(steps) }}" | tr -d '\n')"', "sourcetype":"my-sourcetype", "index":"my-index"}'