name: Python testing

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  python-test-run:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup python3
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        
    - name: install deps
      run: |
        pip3 install hvac
      
    - name: run script
      id: script-output
      run: |
        ls
        python3 scripts/run-python.py
        
    - name: output
      run: |
        echo ${{ steps.script-output.outputs.value }}
       