name: Scan Files

on:
  workflow_dispatch:
  push:
    #branches: ['main']
    #paths: ['apps/**']

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Execute Scan
        run: |
          python ghactions/scripts/scanner_and_replace.py
        env:
          PATTERN: '${{ secrets.PATTERN }}'  # Replace with your pattern
          REPLACEMENT: 'found'  # Replace with your replacement string
