name: Splunk Config Validator
on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  splunk-install-tester:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        
      - name: Install Splunk Universal Forwarder
        run: |
          wget -O splunkforwarder-8.2.5-77015bc7a462-Linux-x86_64.tgz "https://download.splunk.com/products/universalforwarder/releases/8.2.5/linux/splunkforwarder-8.2.5-77015bc7a462-Linux-x86_64.tgz"
          tar -xzf splunkforwarder-8.2.5-77015bc7a462-Linux-x86_64.tgz
          sudo ./splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd changeme
          
      - name: Copy Apps to Splunk Universal Forwarder
        run: |
          sudo cp -r apps/* splunkforwarder/etc/apps/
          sudo ./splunkforwarder/bin/splunk restart
          
      - name: Validate Splunk Universal Forwarder Configurations with btool check
        run: |
          sudo ./splunkforwarder/bin/splunk btool check