name: Update Other Repository
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['lookups/**']

jobs:
  update-code-in-other-repo:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Git Clone repository
        uses: actions/checkout@v3
      
      - name: Set up python/git
        uses: actions/setup-python@v2
          
      - name: Clone other repository
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global credential.helper store
          git clone https://github.com/objectbased/aws-testing.git
          cd aws-testing
          git remote set-url origin "https://objectbased:${{ secrets.ACCESS_TOKEN }}@github.com/objectbased/aws-testing.git"
          git remote set-url --push origin "https://objectbased:${{ secrets.ACCESS_TOKEN }}@github.com/objectbased/aws-testing.git"
          
      - name: Copy file to other repository
        run: |
          cp lookups/* aws-testing/lookups
          ls -la aws-testing/
          
      - name: Set branch name
        run: echo "feature_branch_name=$(date +"%Y-%m-%d")-update-directory" >> $GITHUB_ENV
          
      - name: Commit changes
        env:
           FEATURE_BRANCH_NAME: ${{ env.feature_branch_name }}
        run: |
          cd aws-testing
          ls
          echo "${{ env.feature_branch_name }}"
          git checkout -b $FEATURE_BRANCH_NAME
          git add .
          git commit -m "Update directory with file from original repository"
          git push --set-upstream origin $FEATURE_BRANCH_NAME
          
      - name: Get changed files
        run: echo "diff=$(git diff --name-only main..${{ env.feature_branch_name }})"
          
      - name: Open pull request
        env:
           FEATURE_BRANCH_NAME: ${{ env.feature_branch_name }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/objectbased/aws-testing/pulls \
            -d '{"title": "Update directory with file from original repository", "body": "This pull request updates the directory in the other repository with a file from the original repository.\n\nChanges:\n\n```\n'"${{ steps.changes.outputs.files }}"'\n```", "head": "'$FEATURE_BRANCH_NAME'", "base": "main"}'
