name: Update Other Repository
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['Metrics/**']

jobs:
  update-code-in-other-repo:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Git Clone repository
        uses: actions/checkout@v3
      
      - name: Set up python/git
        uses: actions/setup-python@v2
          
      - name: Clone other repository
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://github.com/objectbased/aws-testing.git
          cd aws-testing
          git remote set-url origin "https://objectbased:${{ secrets.ACCESS_TOKEN }}@github.com/objectbased/aws-testing.git"
          
      - name: Copy file to other repository
        run: |
          cp Metrics/*.csv aws-testing/lookups
          
      - name: Set branch name
        run: echo "feature_branch_name=$(date +"%Y-%m-%d-%H-%M")-${{ github.sha }}" >> $GITHUB_ENV
          
      - name: Commit changes
        env:
           FEATURE_BRANCH_NAME: ${{ env.feature_branch_name }}
        run: |
          cd aws-testing
          git checkout -b $FEATURE_BRANCH_NAME
          git add .
          git commit -m "Update directory with new lookups"
          git push --set-upstream origin $FEATURE_BRANCH_NAME
          
      - name: Open pull request
        env:
           FEATURE_BRANCH_NAME: ${{ env.feature_branch_name }}
           DIFF: ${{ env.diff }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/objectbased/aws-testing/pulls \
            -d '{"title": "Update directory with file from original repository", "body": "Workflow triggered to update latest commit in repo-abc-123 with lookup in repo-zfg-456", "head": "'$FEATURE_BRANCH_NAME'", "base": "main"}'