name: vector syntax check
on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
    paths: ['vector/**']
    
jobs:
  vector-config-check:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Git clone
    uses: actions/checkout@v4
    with:
      spare-checkout: |
        vector/configs
        
    - name: install vector
    run: |
      bash -c "$(curl -L https://setup.vector.dev)"
      sudo apt-get install vector
      
    - name: copy configs
    run: |
      mkdir /etc/vector/configs
      sudo cp -r vector/configs/* /etc/vector/configs
      
    - name: validate
    run: |
      vector validate /etc/vector/configs/*.yaml