name: vector syntax check
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['vector/**']
    
jobs:
  vector-config-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Git clone
      uses: actions/checkout@v4
        
    - name: install vector
      run: |
        bash -c "$(curl -L https://setup.vector.dev)"
        sudo apt-get install vector
        ls
        which vector
      
    - name: copy configs
      run: |
        mkdir /usr/bin/vector/configs
        sudo cp -r vector/configs/* /usr/bin/vector/configs
      
    - name: validate
      run: |
        vector validate /usr/bin/vector/configs/*.yaml